server:
  port: ${PORT}

spring:
  datasource:
    url: ${DB_URL}
    driverClassName: org.h2.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
  mvc:
    servlet:
      path: /api

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

admin:
  email: ${ADMIN_EMAIL}

products:
  imgsDir: ${PRODUCTS_IMGS_DIR}